language: python

python: 
  - "3.6"

git:
  depth: 1

install:
  - pip install -r requirements.txt

env: 
  - TRAVIS_SECURE_ENV_VARS=true

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test backend --verbosity 2
  - python3 manage.py test frontend/tests --verbosity 2
  - coverage run --source='.' manage.py test myapp
  - coverage report