language: python

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


python: 
  - "3.6"

git:
  depth: 1

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

install:
  - pip install -r requirements.txt

env: 
  - TRAVIS_SECURE_ENV_VARS=true

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - python manage.py makemigrations
  - python manage.py migrate
  
script:
  - coverage run --source='.' manage.py test frontend/tests
  - coverage report
