# Generated by Django 2.1.1 on 2018-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181118_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
